### ISSUE TITLE
fatal error - internal  error reading the windows environment - too many environment variables

### ISSUE THREAD

**Issue by boustrephon** [Anaconda-Platform/anaconda-nb-extensions#167]
I realize that this probably not a problem with your packages, but I wonder if anyone can help me to sort out this problem.

Andrew

```
C:\Users\andrew.mole\Source\anaconda-nb-extensions>conda build conda.recipe
Cloning into bare repository 'C:\ProgramData\Anaconda3\conda-bld\git_cache\C_\Users\andrew.mole\So
urce\anaconda-nb-extensions'...
      0 [main] sh 3148 C:\ProgramData\Anaconda3\Library\usr\bin\sh.exe: *** fatal error - internal
 error reading the windows environment - too many environment variables?
    850 [main] sh 3148 cygwin_exception::open_stackdumpfile: Dumping stack trace to sh.exe.stackdu
mp
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Cloning into bare repository 'C:\ProgramData\Anaconda3\conda-bld\git_cache\C_\Users\andrew.mole\So
urce\anaconda-nb-extensions'...
      0 [main] sh 12220 C:\ProgramData\Anaconda3\Library\usr\bin\sh.exe: *** fatal error - interna
l error reading the windows environment - too many environment variables?
   1024 [main] sh 12220 cygwin_exception::open_stackdumpfile: Dumping stack trace to sh.exe.stackd
ump
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Warning: failed to download source.  If building, will try again after downloading recipe dependen
cies.
Error was:
Command '['C:\\ProgramData\\Anaconda3\\Library\\bin\\git.exe', 'clone', '--mirror', 'C:\\Users\\an
drew.mole\\Source\\anaconda-nb-extensions', 'C:\\ProgramData\\Anaconda3\\conda-bld\\git_cache\\C_\
\Users\\andrew.mole\\Source\\anaconda-nb-extensions']' returned non-zero exit status 128.
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Cloning into bare repository 'C:\ProgramData\Anaconda3\conda-bld\git_cache\C_\Users\andrew.mole\So
urce\anaconda-nb-extensions'...
      0 [main] sh 22472 C:\ProgramData\Anaconda3\Library\usr\bin\sh.exe: *** fatal error - interna
l error reading the windows environment - too many environment variables?
   1000 [main] sh 22472 cygwin_exception::open_stackdumpfile: Dumping stack trace to sh.exe.stackd
ump
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Cloning into bare repository 'C:\ProgramData\Anaconda3\conda-bld\git_cache\C_\Users\andrew.mole\So
urce\anaconda-nb-extensions'...
      0 [main] sh 14624 C:\ProgramData\Anaconda3\Library\usr\bin\sh.exe: *** fatal error - interna
l error reading the windows environment - too many environment variables?
    869 [main] sh 14624 cygwin_exception::open_stackdumpfile: Dumping stack trace to sh.exe.stackd
ump
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\source.py", line 223, in git_mirror
_checkout_recursive
    check_call_env(args + [git_url, git_mirror_dir], stdout=stdout, stderr=stderr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\utils.py", line 678, in check_call_
env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\utils.py", line 674, in _func_defau
lting_env_to_os_environ
    return func(_args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\ProgramData\\Anaconda3\\Library\\bin\\git.exe', 'clo
ne', '--mirror', 'C:\\Users\\andrew.mole\\Source\\anaconda-nb-extensions', 'C:\\ProgramData\\Anaco
nda3\\conda-bld\\git_cache\\C_\\Users\\andrew.mole\\Source\\anaconda-nb-extensions']' returned non
-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\source.py", line 629, in provide
    verbose=metadata.config.verbose)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\source.py", line 314, in git_source
    git_depth=git_depth, is_top_level=True, verbose=verbose)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\source.py", line 233, in git_mirror
_checkout_recursive
    check_call_env(args + [git_url, git_mirror_dir], stdout=stdout, stderr=stderr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\utils.py", line 678, in check_call_
env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\utils.py", line 674, in _func_defau
lting_env_to_os_environ
    return func(_args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\ProgramData\\Anaconda3\\Library\\bin\\git.exe', 'clo
ne', '--mirror', 'C:\\Users\\andrew.mole\\Source\\anaconda-nb-extensions', 'C:\\ProgramData\\Anaco
nda3\\conda-bld\\git_cache\\C_\\Users\\andrew.mole\\Source\\anaconda-nb-extensions']' returned non
-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\conda-build-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\cli\main_build.py", line 413, in ma
in
    execute(sys.argv[1:])
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\cli\main_build.py", line 404, in ex
ecute
    verify=args.verify)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\api.py", line 193, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\build.py", line 1944, in build_tree
    notest=notest,
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\build.py", line 1029, in build
    try_download(m, no_download_source=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\render.py", line 469, in try_downlo
ad
    source.provide(metadata)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\source.py", line 657, in provide
    os.rename(metadata.config.work_dir, metadata.config.work_dir + '_failed_provide')
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\ProgramDa
ta\\Anaconda3\\conda-bld\\anaconda-nb-extensions_1517826729805\\work' -> 'C:\\ProgramData\\Anacond
a3\\conda-bld\\anaconda-nb-extensions_1517826729805\\work_failed_provide'
```

**Comment by damianavila** [comment]
@boustrephon has not received updates in 2 years and it is not maintained.
I would suggest just install the extensions from the main channel or conda-forge.
Thanks!

**Comment by boustrephon** [comment]
@damianavila 
Thank you for the swift response. The reason I was trying to build my own was that there isn't a version  for Python 3.6 (as far as I can see, anyway). Do I just have to wait for conda-forge to build one?

I am still trying to understand the error message about environment variables. There is a hint that it is related to the order of the paths in the PATH environment variable.

**Comment by damianavila** [comment]
> The reason I was trying to build my own was that there isn't a version for Python 3.6 (as far as I can see, anyway). Do I just have to wait for conda-forge to build one?

There are versions of the packages in python 3.6 from conda forge and from main as well. This thing was essentially a meta package to install all the extension. But I recommend you to install the extensions ones by one.
